possible_board_entries=[
		"cringe thing 1",
		"cringe thing 2",
		"cringe thing 3",
		"cringe thing 4",
		"cringe thing 5",
		"cringe thing 6",
		"cringe thing 7",
		"cringe thing 8",
		"cringe thing 9",
		"cringe thing 10",
		"cringe thing 11",
		"cringe thing 12",
		"cringe thing 13",
		"cringe thing 14",
		"cringe thing 15",
		"cringe thing 16",
		"cringe thing 17",
		"cringe thing 18",
		"cringe thing 19",
		"cringe thing 20",
		"cringe thing 21",
		"cringe thing 22",
		"cringe thing 23",
		"cringe thing 24",
		"cringe thing 25",
		"cringe thing 26",
		"cringe thing 27"]; // etc
